#!/bin/sh

# updates to the default revision number or takes in revision number on call
#  

WEB_DIR=/var/www/htdocs/prestissimo/
APACHECTL=/etc/rc.d/rc.httpd
SVNCMD=/usr/bin/svn
BUNDLE=/usr/local/bin/bundle
WEBUSER="apache"
REVNUM="885"

# verify command run as root 
if [ `whoami` != 'apache' ]; then
        echo "Need to be apache to run fixit"
        exit 1
fi

# get the revision number
if [ $# -gt 0 -a ! -z "$1" ]
then
  REVNUM="$1"
fi

# go to apache's svn co
cd $WEB_DIR

echo "*** Pulling from svn repository..."

echo -n "    Enter OCCS username: "
read OCCS_USER

echo -n "    Enter OCCS password: "
stty -echo
read OCCS_PASSWD
stty echo
echo

# update svn checkout
$SVNCMD up --revision "$REVNUM" --non-interactive --trust-server-cert --no-auth-cache --username "$OCCS_USER" --password "$OCCS_PASSWD"
if [ $? -ne 0 ]; then
    echo "svn up failed"
    exit 2
fi

# deploy
echo
echo "*** Precompiling assets..."
$BUNDLE exec rake assets:precompile
if [ $? -ne 0 ];
then
    echo "Failed!"
    exit 4
fi

# restart apache server
echo
echo "*** Restarting apache server..."
sudo $APACHECTL restart
if [ $? -ne 0 ];
then
    echo "Failed!"
    exit 5
fi

echo "Successfully fixed it!"
