#!/bin/sh

# run this as root to bring the .info server up to the current svn revision
# the database is migrated (not reset, this needs to be done manually)

WEB_DIR=/var/www/htdocs/prestissimo/
APACHECTL=/usr/sbin/apachectl
SVNCMD=/usr/bin/svn
BUNDLE=/usr/local/bin/bundle
WEBUSER="apache"

# sign in as apache
if [ `id -u` -ne 0 ]; then
        echo "Need to be root to run fixit"
        exit 1
fi

# go to apache's svn co
cd $WEB_DIR

echo "*** Pulling from svn repository..."

echo -n "    Enter OCCS username: "
read OCCS_USER

echo -n "    Enter OCCS password: "
stty -echo
read OCCS_PASSWD
stty echo
echo

# update svn checkout
sudo -u $WEBUSER $SVNCMD up --non-interactive --trust-server-cert --no-auth-cache --username "$OCCS_USER" --password "$OCCS_PASSWD"
if [ $? -ne 0 ]; then
    echo "svn up failed"
    exit 2
fi

# update database
echo
echo "*** Updating production database..."
sudo -u $WEBUSER $BUNDLE exec rake db:migrate RAILS_ENV="production"
if [ $? -ne 0 ]; then
    echo "Failed!"
    exit 3
fi

# deploy
echo
echo "*** Precompiling assets..."
sudo -u $WEBUSER $BUNDLE exec rake assets:precompile
if [ $? -ne 0 ];
then
    echo "Failed!"
    exit 4
fi

# restart apache server
echo
echo "*** Restarting apache server..."
$APACHECTL restart
if [ $? -ne 0 ];
then
    echo "Failed!"
    exit 5
fi

echo "Successfully fixed it!"
