module UsersHelper
  def getUrl(major) # this used to just include departments that were also majors, but now includes more, so the "major" tag is a bit misleading
    links = { 'AAST' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4344',
              'ANTH' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4345',
              'ARBC' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4347',
              'ACHS' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4348',
              'ARTS' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4349',
              'APST' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4346',
              'ASTR' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4460',
              'ATHL' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4355',
              'BIOL' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4375',
              'CHEM' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4376',
              'CHIN' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4391',
              'CINE' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4377',
              'CLAS' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4378',
              'CAST' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4381',
              'CMPL' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4382',
              'CNST' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4386',
              'CMUS' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4448',
              'CSCI' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4384',
              'CRWR' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4388',
              'COMP' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4356',
              'DANC' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4389',
              'EAST' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4391',
              'ECON' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4392',
              'EDPR' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4393',
              'ENTR' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4412',
              'EDUC' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4393',
              'EDUA' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4393',
              'ENGL' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4396',
              'ESOL' => 'http://catalog.oberlin.edu/preview_entity.php?catoid=35&ent_oid=2875',
              'ENVS' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4398',
              'ETHN' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4433',
              'FYSP' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4400',
              'FREN' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4401',
              'ITAL' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4401',
              'GSFS' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4402',
              'GEOL' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4403',
              'GERM' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4404',
              'GREK' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4378',
              'HLTH' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4477',
              'HISP' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4406',
              'HIST' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4408',
              'HPRF' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4407',
              'JAPN' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4391',
              'INDV' => 'http://new.oberlin.edu/office/dean-of-studies/individual-majors/',
              'JAZZ' => 'http://catalog.oberlin.edu/preview_entity.php?catoid=35&ent_oid=2863',
              'JWST' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4415',
              'LANG' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4416',
              'LATS' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4417',
              'LATN' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4378',
              'LOND' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4420',
              'LRNS' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4419',
              'MATH' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4429',
              'MLIT' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4446',
              'MUED' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4445',
              'MUTH' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4360',
              'MHST' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4359',
              'NSCI' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4450',
              'OPTH' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4452',
              'PHIL' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4459',
              'PHYS' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4460',
              'POLT' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4461',
              'PORT' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4482',
              'PSYC' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4463',
              'PVST' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4462',
              'RELG' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4465',
              'RHET' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4466',
              'REES' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4467',
              'RTCP' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4476',
              'RUSS' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4468',
              'SOCI' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4469',
              'STAT' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4473',
              'TECH' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4470',
              'THEA' => 'http://catalog.oberlin.edu/preview_program.php?catoid=35&poid=4471',
              'TWST' => 'http://catalog.oberlin.edu/preview_program.php?catoid=33&poid=4073&returnto=763' }

    links[major]
  end
end
