#!/bin/sh

# findit searches the app directory looking for a certain search query
# It ignores binary files, svn files and other extra files

USAGE='findit usage: findit [ -help || -assets || -helpers || -conts || -views || -models || -app || -home ]'
HELP="Help: findit searches the given directory for any \
    instance of a given search query. It returns the files in which the search query appears \
    and gives the number of hits for each file. Each flag corresponds to a direcorty, i.e. -helpers is \
    ~/prestissimo/app/helpers, -home is ~/prestissimo/."
BASE="`echo $HOME`/prestissimo"

if [ $# -lt 1 ] ; then
    echo $USAGE
    exit 1
else
    if [[ $1 == '-help' ]] ; then
	echo $HELP
	exit 1
    elif [[ $1 == '-home' ]] ; then
	#BASE="~/prestissimo/"
	echo $BASE
	shift
    elif [[ $1 == '-app' ]] ; then
	BASE="$BASE/app"
	echo $BASE
	shift
    elif [[ $1 == '-models' ]] ; then
	BASE="$BASE/app/models"
	echo $BASE
	shift
    elif [[ $1 == '-views' ]] ; then
	BASE="$BASE/app/views"
	echo $BASE
	shift
    elif [[ $1 == '-conts' ]] ; then
	BASE="$BASE/app/controllers"
	echo $BASE
	shift
    elif [[ $1 == '-helpers' ]] ; then
	BASE="$BASE/app/helpers"
	echo $BASE
	shift
    elif [[ $1 == '-assets' ]] ; then
	BASE="$BASE/app/assets"
	echo $BASE
	shift
    else
	echo $USAGE
	exit 1
    fi
fi

###QUERY stuff###

QUERY=""

show_results(){
    COUNTER=0
    CUR_FILE=""
    FILE_NUM=1

    cat temp | cut -d':' -f1 > files

    if [ -s files ] ; then
	FILE_SIZE=`wc -l files`
	#CUR_FILE=`sed -n "$line_num{p}" files`
	echo $CUR_FILE
	cat temp
    else
	echo "No results found."
    fi

    
    
    #rm files
}

#function to actually find the query
find_query()
{
    find $BASE | xargs grep -n "$QUERY" | egrep -v 'svn' | egrep -v '~:' | cut -d'/' -f5- > temp
    #cat temp
    show_results

    #find ~/prestissimo/app | xargs grep "$QUERY"
    rm temp
    rm files
}

while [ 1 ] ; do
    echo "Enter search query (q to quit):"
    read QUERY
    if [[ $QUERY == 'q' ]] ; then
	exit 0
    fi
    find_query
done

