#!/bin/sh

# run this as root to bring the .info server up to the current svn revision
# the database is migrated (not reset, this needs to be done manually)

RUBYV="ruby-2.2.2" # Change this for a different ruby version
WEB_DIR="/var/www/html/oprestissimo.com/"
GITCMD="/usr/bin/git"
BUNDLE="/usr/share/rvm/rubies/$RUBYV/bin/bundle"
RAKE="/usr/share/rvm/rubies/$RUBYV/bin/rake"
RUBYBIN="/usr/share/rvm/rubies/$RUBYV/bin"
SUPARAMS="export PATH=\$PATH:$RUBYBIN;"
WEBUSER="oprestissimo"

# sign in as web user
if [ `id -u` -ne 0 ]; then
        echo "Need to be root to run fixit"
        exit 1
fi

#sudo su $WEBUSER -c "env PATH=\$PATH:$RUBYBIN; export PATH"
sudo su $WEBUSER -c "$SUPARAMS echo \$PATH"

# go to apache's svn co
cd $WEB_DIR

echo "*** Pulling from git repository..."

# git pull
sudo su $WEBUSER -c "git stash"
sudo git pull
if [ $? -ne 0 ]; then
    echo "git pull failed"
    exit 2
fi

echo "*** Bundle update and install..."

# bundle update
# sudo $BUNDLE update --quiet
# if [ $? -ne 0 ]; then
#     echo "Failed!"
#     exit 6
# fi

# bundle install
# sudo su $WEBUSER -c "$SUPARAMS $BUNDLE install --quiet"
# if [ $? -ne 0 ]; then
#     echo "Failed!"
#     exit 7
# fi

# update database
echo
echo "*** Updating database..."
sudo su $WEBUSER -c "$SUPARAMS $BUNDLE exec $RAKE db:migrate RAILS_ENV=production" # Need to specify RAILS_ENV for production
if [ $? -ne 0 ]; then
    echo "Failed!"
    exit 3
fi

#echo
#echo "*** Updating documentation files..."
#sudo su $WEBUSER -c "$SUPARAMS $BUNDLE exec $RAKE doc:app"
#if [ $? -ne 0 ]; then
#    echo "Failed!"
#    exit 6
#fi

# deploy
echo
echo "*** Precompiling assets..."
sudo su $WEBUSER -c "$SUPARAMS $BUNDLE exec $RAKE assets:precompile RAILS_ENV=production"
if [ $? -ne 0 ];
then
    echo "Failed!"
    exit 4
fi

# restart apache server
echo
echo "*** Restarting apache server..."
sudo systemctl restart apache2.service
if [ $? -ne 0 ];
then
    echo "Failed!"
    exit 5
fi

echo "Successfully fixed it!"
