#!/bin/sh

# run this as root to bring the .info server up to the current svn revision
# the database is migrated (not reset, this needs to be done manually)

RUBYV="ruby-2.2.2" # Change this for a different ruby version
WEB_DIR=/var/www/html/oprestissimo.com/
GITCMD=/usr/bin/git
BUNDLE=/usr/share/rvm/rubies/$RUBYV/bin/bundle
WEBUSER="svradm"

echo $BUNDLE

# sign in as apache
if [ `id -u` -ne 0 ]; then
        echo "Need to be root to run fixit"
        exit 1
fi

# go to apache's svn co
cd $WEB_DIR

echo "*** Pulling from git repository..."

# git pull
sudo git pull
if [ $? -ne 0 ]; then
    echo "git pull failed"
    exit 2
fi

# update database
echo
echo "*** Updating database..."
sudo -u $WEBUSER bundle exec rake db:migrate # Need to specify RAILS_ENV for production
if [ $? -ne 0 ]; then
    echo "Failed!"
    exit 3
fi

echo
echo "*** Updating documentation files ***"
sudo -u $WEBUSER $BUNDLE exec rake doc:app
if [ $? -ne 0 ]; then
    echo "Failed!"
    exit 6
fi

# deploy
echo
echo "*** Precompiling assets..."
sudo -u $WEBUSER $BUNDLE exec rake assets:precompile
if [ $? -ne 0 ];
then
    echo "Failed!"
    exit 4
fi

# restart apache server
echo
echo "*** Restarting apache server..."
sudo systemctl restart apache2.service
if [ $? -ne 0 ];
then
    echo "Failed!"
    exit 5
fi

echo "Successfully fixed it!"
